# Utilizza un'immagine di base con Java 11
FROM openjdk:latest

# Imposta la porta su cui l'applicazione sarà in ascolto
EXPOSE 16000

# Avvia l'applicazione Spring Boot
CMD ["java", "-jar", "/app/xacml_server.jar"]
